// Generated by tools/dashboard_gen.py from NBS_Scaling_Quanti_v8.mdl — do not edit by hand.
export const CITIES = [
  {
    "name": "Cork",
    "population": 222333.0,
    "rows": [
      {
        "var": "Population",
        "label": "Residents",
        "unit": "people",
        "dp": 0,
        "values": [
          66700.0,
          155633.0
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Cork: 222,333 residents (proposal Table 4). The split between neighbourhood types is PROVISIONAL: 30 percent of residents in deprived areas, as in the generic city, until WP3 maps the city's deprived areas (for example the most deprived fifth of small areas, from the national deprivation index)."
      },
      {
        "var": "Land Area",
        "label": "Land area",
        "unit": "ha",
        "dp": 0,
        "values": [
          889.0,
          3557.0
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Cork. Residential land at the generic city's densities (75 residents per hectare in deprived areas, 44 elsewhere) until WP3 maps a harmonised urban core. The administrative density in proposal Table 4 is not used: for Lahti and Klagenfurt it includes forest, farmland and lakes, which would make these cities look greener than their residents' surroundings are (feasibility test, 2026-09-19)."
      },
      {
        "var": "Background Green Cover",
        "label": "Background green cover",
        "unit": "%",
        "dp": 1,
        "values": [
          0.06,
          0.14
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Cork: the generic city's values, pending the decision on what green cover means (v5.1 evidence, decision 1). Harmonised data ready for either definition, ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health: green area 19.7 percent of land within 300 m of homes (Urban Atlas 2012; publicly designated green space) and NDVI 0.538 (all vegetation)."
      },
      {
        "var": "Initial NBS Cover",
        "label": "Public green at the start",
        "unit": "%",
        "dp": 1,
        "values": [
          0.04,
          0.08
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Cork: the generic city's values. To come from the city's own inventory of parks, street trees and other green infrastructure it maintains, or from Urban Atlas 'green urban areas' (WP3)."
      },
      {
        "var": "Municipal NBS Budget",
        "label": "NBS budget",
        "unit": "k EUR/yr",
        "dp": 0,
        "values": [
          10461.0
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, calibrated, Cork: 47 euro per resident a year (222,333 residents). Chosen so that the city's public green is roughly stable from 2012, the neutral assumption while the real budget is unknown. The generic city's 96 euro per resident instead implied a 31 percent expansion of public green by 2026, which no European city has achieved (plausibility.py). At this budget the model spends about 33 thousand euro a year per hectare of public green, covering renewal and the municipal organisation as well as upkeep; city park agencies spend on average 12.7 thousand US dollars per hectare on operations alone, range 3.2 to 54.9 (KPMG, Park access, 2017), and UK parks services about 20 to 30 pounds per resident. Replace with the city's reported NBS spending (WP5), or calibrate against the observed change in public green (Urban Atlas 2012, 2018, 2021)."
      },
      {
        "var": "Annual Death Rate",
        "label": "Death rate",
        "unit": "per 1,000/yr",
        "dp": 1,
        "values": [
          0.0073
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Cork. Crude death rate 7.3 per 1,000 residents, NUTS 3 region IE053 South-West (Cork and Kerry), 2023 (Eurostat demo_r_gind3). The region is wider than the city."
      },
      {
        "var": "Baseline Nature Engagement",
        "label": "Use green space without a programme",
        "unit": "%",
        "dp": 0,
        "values": [
          0.436,
          0.523
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Cork. Special Eurobarometer 525 (2022): 41 percent of physically active adults in Ireland exercise in a park or outdoors, against 47 percent in the EU. The generic values (0.5, 0.6; White et al. 2019) are scaled by 41/47. National figure; WP4 surveys can replace it."
      },
      {
        "var": "Background Fine Particulates",
        "label": "PM2.5 before policy",
        "unit": "ug/m3",
        "dp": 1,
        "values": [
          8.37,
          6.7
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Cork. Annual mean PM2.5 7.2 micrograms per cubic metre, ranked 834 of 858 European cities (ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health; proposal Table 4). The split between neighbourhood types is PROVISIONAL, as in the generic city (deprived areas 25 percent higher), with the population-weighted mean equal to 7.2."
      },
      {
        "var": "Poor Mental Health Prevalence",
        "label": "Poor mental health",
        "unit": "%",
        "dp": 1,
        "values": [
          0.07
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Cork. Eurostat EHIS 2019 (hlth_ehis_mh1e): 4.9 percent of adults in Ireland report current depressive symptoms, against 7.0 percent in the EU. The generic value (0.10, depression and anxiety, IHME) is scaled by 4.9/7.0. National figure."
      },
      {
        "var": "Delivery Cost per Hectare",
        "label": "Cost to deliver a hectare",
        "unit": "k EUR/ha",
        "dp": 0,
        "values": [
          192.6
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Cork. Eurostat price level index for construction, 2024 (prc_ppp_ind, EU27 = 100): Ireland 96.3. The generic cost (200, an EU-average city) is scaled by 96.3/100. National figure."
      },
      {
        "var": "Green Cover at Half Access",
        "label": "Green cover at half access",
        "unit": "",
        "dp": 3,
        "values": [
          0.6671
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, calibrated, Cork. 78.73 percent of residents live where green area within 300 m is below the 25 percent that provides WHO-recommended access (ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health; proposal Table 4), so access is 21.27 percent. The value is solved so that the model's access at time 0 matches, given the provisional green cover above; it will be recalibrated when the city's green cover is measured. It measures how well a city's green space is spread among its homes: low where green is close to most residents."
      }
    ],
    "id": "Cork",
    "blurb": "Ireland. Low green-space access: 79% of residents live below the WHO-based target."
  },
  {
    "name": "Klagenfurt",
    "population": 103009.0,
    "rows": [
      {
        "var": "Population",
        "label": "Residents",
        "unit": "people",
        "dp": 0,
        "values": [
          30903.0,
          72106.0
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Klagenfurt: 103,009 residents (proposal Table 4). The split between neighbourhood types is PROVISIONAL: 30 percent of residents in deprived areas, as in the generic city, until WP3 maps the city's deprived areas (for example the most deprived fifth of small areas, from the national deprivation index)."
      },
      {
        "var": "Land Area",
        "label": "Land area",
        "unit": "ha",
        "dp": 0,
        "values": [
          412.0,
          1648.0
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Klagenfurt. Residential land at the generic city's densities (75 residents per hectare in deprived areas, 44 elsewhere) until WP3 maps a harmonised urban core. The administrative density in proposal Table 4 is not used: for Lahti and Klagenfurt it includes forest, farmland and lakes, which would make these cities look greener than their residents' surroundings are (feasibility test, 2026-09-19)."
      },
      {
        "var": "Background Green Cover",
        "label": "Background green cover",
        "unit": "%",
        "dp": 1,
        "values": [
          0.06,
          0.14
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Klagenfurt: the generic city's values, pending the decision on what green cover means (v5.1 evidence, decision 1). Harmonised data ready for either definition, ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health: green area 48.4 percent of land within 300 m of homes (Urban Atlas 2012; publicly designated green space) and NDVI 0.581 (all vegetation)."
      },
      {
        "var": "Initial NBS Cover",
        "label": "Public green at the start",
        "unit": "%",
        "dp": 1,
        "values": [
          0.04,
          0.08
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Klagenfurt: the generic city's values. To come from the city's own inventory of parks, street trees and other green infrastructure it maintains, or from Urban Atlas 'green urban areas' (WP3)."
      },
      {
        "var": "Municipal NBS Budget",
        "label": "NBS budget",
        "unit": "k EUR/yr",
        "dp": 0,
        "values": [
          5622.0
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, calibrated, Klagenfurt: 55 euro per resident a year (103,009 residents). Chosen so that the city's public green is roughly stable from 2012, the neutral assumption while the real budget is unknown. The generic city's 96 euro per resident instead implied a 31 percent expansion of public green by 2026, which no European city has achieved (plausibility.py). At this budget the model spends about 38 thousand euro a year per hectare of public green, covering renewal and the municipal organisation as well as upkeep; city park agencies spend on average 12.7 thousand US dollars per hectare on operations alone, range 3.2 to 54.9 (KPMG, Park access, 2017), and UK parks services about 20 to 30 pounds per resident. Replace with the city's reported NBS spending (WP5), or calibrate against the observed change in public green (Urban Atlas 2012, 2018, 2021)."
      },
      {
        "var": "Annual Death Rate",
        "label": "Death rate",
        "unit": "per 1,000/yr",
        "dp": 1,
        "values": [
          0.011
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Klagenfurt. Crude death rate 11.0 per 1,000 residents, NUTS 3 region AT211 Klagenfurt-Villach, 2023 (Eurostat demo_r_gind3). The region is wider than the city."
      },
      {
        "var": "Baseline Nature Engagement",
        "label": "Use green space without a programme",
        "unit": "%",
        "dp": 0,
        "values": [
          0.649,
          0.779
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Klagenfurt. Special Eurobarometer 525 (2022): 61 percent of physically active adults in Austria exercise in a park or outdoors, against 47 percent in the EU. The generic values (0.5, 0.6; White et al. 2019) are scaled by 61/47. National figure; WP4 surveys can replace it."
      },
      {
        "var": "Background Fine Particulates",
        "label": "PM2.5 before policy",
        "unit": "ug/m3",
        "dp": 1,
        "values": [
          15.58,
          12.47
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Klagenfurt. Annual mean PM2.5 13.4 micrograms per cubic metre, ranked 361 of 858 European cities (ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health; proposal Table 4). The split between neighbourhood types is PROVISIONAL, as in the generic city (deprived areas 25 percent higher), with the population-weighted mean equal to 13.4."
      },
      {
        "var": "Poor Mental Health Prevalence",
        "label": "Poor mental health",
        "unit": "%",
        "dp": 1,
        "values": [
          0.08
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Klagenfurt. Eurostat EHIS 2019 (hlth_ehis_mh1e): 5.6 percent of adults in Austria report current depressive symptoms, against 7.0 percent in the EU. The generic value (0.10, depression and anxiety, IHME) is scaled by 5.6/7.0. National figure."
      },
      {
        "var": "Delivery Cost per Hectare",
        "label": "Cost to deliver a hectare",
        "unit": "k EUR/ha",
        "dp": 0,
        "values": [
          223.4
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Klagenfurt. Eurostat price level index for construction, 2024 (prc_ppp_ind, EU27 = 100): Austria 111.7. The generic cost (200, an EU-average city) is scaled by 111.7/100. National figure."
      },
      {
        "var": "Green Cover at Half Access",
        "label": "Green cover at half access",
        "unit": "",
        "dp": 3,
        "values": [
          0.332
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, calibrated, Klagenfurt. 65.16 percent of residents live where green area within 300 m is below the 25 percent that provides WHO-recommended access (ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health; proposal Table 4), so access is 34.84 percent. The value is solved so that the model's access at time 0 matches, given the provisional green cover above; it will be recalibrated when the city's green cover is measured. It measures how well a city's green space is spread among its homes: low where green is close to most residents."
      }
    ],
    "id": "Klagenfurt",
    "blurb": "Austria. Green on the map, but two thirds of residents still lack nearby green space."
  },
  {
    "name": "Lahti (Päijät-Häme)",
    "population": 120122.0,
    "rows": [
      {
        "var": "Population",
        "label": "Residents",
        "unit": "people",
        "dp": 0,
        "values": [
          36037.0,
          84085.0
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Lahti: 120,122 residents (proposal Table 4). The split between neighbourhood types is PROVISIONAL: 30 percent of residents in deprived areas, as in the generic city, until WP3 maps the city's deprived areas (for example the most deprived fifth of small areas, from the national deprivation index)."
      },
      {
        "var": "Land Area",
        "label": "Land area",
        "unit": "ha",
        "dp": 0,
        "values": [
          480.0,
          1922.0
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Lahti. Residential land at the generic city's densities (75 residents per hectare in deprived areas, 44 elsewhere) until WP3 maps a harmonised urban core. The administrative density in proposal Table 4 is not used: for Lahti and Klagenfurt it includes forest, farmland and lakes, which would make these cities look greener than their residents' surroundings are (feasibility test, 2026-09-19)."
      },
      {
        "var": "Background Green Cover",
        "label": "Background green cover",
        "unit": "%",
        "dp": 1,
        "values": [
          0.06,
          0.14
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Lahti: the generic city's values, pending the decision on what green cover means (v5.1 evidence, decision 1). Harmonised data ready for either definition, ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health: green area 43.7 percent of land within 300 m of homes (Urban Atlas 2012; publicly designated green space) and NDVI 0.529 (all vegetation)."
      },
      {
        "var": "Initial NBS Cover",
        "label": "Public green at the start",
        "unit": "%",
        "dp": 1,
        "values": [
          0.04,
          0.08
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Lahti: the generic city's values. To come from the city's own inventory of parks, street trees and other green infrastructure it maintains, or from Urban Atlas 'green urban areas' (WP3)."
      },
      {
        "var": "Municipal NBS Budget",
        "label": "NBS budget",
        "unit": "k EUR/yr",
        "dp": 0,
        "values": [
          6538.0
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, calibrated, Lahti: 54 euro per resident a year (120,122 residents). Chosen so that the city's public green is roughly stable from 2012, the neutral assumption while the real budget is unknown. The generic city's 96 euro per resident instead implied a 31 percent expansion of public green by 2026, which no European city has achieved (plausibility.py). At this budget the model spends about 38 thousand euro a year per hectare of public green, covering renewal and the municipal organisation as well as upkeep; city park agencies spend on average 12.7 thousand US dollars per hectare on operations alone, range 3.2 to 54.9 (KPMG, Park access, 2017), and UK parks services about 20 to 30 pounds per resident. Replace with the city's reported NBS spending (WP5), or calibrate against the observed change in public green (Urban Atlas 2012, 2018, 2021)."
      },
      {
        "var": "Annual Death Rate",
        "label": "Death rate",
        "unit": "per 1,000/yr",
        "dp": 1,
        "values": [
          0.0135
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Lahti. Crude death rate 13.5 per 1,000 residents, NUTS 3 region FI1C3 Paijat-Hame, 2022 (latest published) (Eurostat demo_r_gind3). The region is wider than the city."
      },
      {
        "var": "Baseline Nature Engagement",
        "label": "Use green space without a programme",
        "unit": "%",
        "dp": 0,
        "values": [
          0.702,
          0.843
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Lahti. Special Eurobarometer 525 (2022): 66 percent of physically active adults in Finland exercise in a park or outdoors, against 47 percent in the EU. The generic values (0.5, 0.6; White et al. 2019) are scaled by 66/47. National figure; WP4 surveys can replace it."
      },
      {
        "var": "Background Fine Particulates",
        "label": "PM2.5 before policy",
        "unit": "ug/m3",
        "dp": 1,
        "values": [
          6.74,
          5.4
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Lahti. Annual mean PM2.5 5.8 micrograms per cubic metre, ranked 851 of 858 European cities (ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health; proposal Table 4). The split between neighbourhood types is PROVISIONAL, as in the generic city (deprived areas 25 percent higher), with the population-weighted mean equal to 5.8."
      },
      {
        "var": "Poor Mental Health Prevalence",
        "label": "Poor mental health",
        "unit": "%",
        "dp": 1,
        "values": [
          0.093
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Lahti. Eurostat EHIS 2019 (hlth_ehis_mh1e): 6.5 percent of adults in Finland report current depressive symptoms, against 7.0 percent in the EU. The generic value (0.10, depression and anxiety, IHME) is scaled by 6.5/7.0. National figure."
      },
      {
        "var": "Delivery Cost per Hectare",
        "label": "Cost to deliver a hectare",
        "unit": "k EUR/ha",
        "dp": 0,
        "values": [
          222.8
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Lahti. Eurostat price level index for construction, 2024 (prc_ppp_ind, EU27 = 100): Finland 111.4. The generic cost (200, an EU-average city) is scaled by 111.4/100. National figure."
      },
      {
        "var": "Green Cover at Half Access",
        "label": "Green cover at half access",
        "unit": "",
        "dp": 3,
        "values": [
          0.0815
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, calibrated, Lahti. 32.4 percent of residents live where green area within 300 m is below the 25 percent that provides WHO-recommended access (ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health; proposal Table 4), so access is 67.60 percent. The value is solved so that the model's access at time 0 matches, given the provisional green cover above; it will be recalibrated when the city's green cover is measured. It measures how well a city's green space is spread among its homes: low where green is close to most residents."
      }
    ],
    "id": "Lahti",
    "blurb": "Finland, the Päijät-Häme pilot. The most accessible green space of the four, and the highest park use in Europe."
  },
  {
    "name": "Malta",
    "population": 533286.0,
    "rows": [
      {
        "var": "Population",
        "label": "Residents",
        "unit": "people",
        "dp": 0,
        "values": [
          159986.0,
          373300.0
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Malta: 533,286 residents (proposal Table 4). The split between neighbourhood types is PROVISIONAL: 30 percent of residents in deprived areas, as in the generic city, until WP3 maps the city's deprived areas (for example the most deprived fifth of small areas, from the national deprivation index)."
      },
      {
        "var": "Land Area",
        "label": "Land area",
        "unit": "ha",
        "dp": 0,
        "values": [
          2133.0,
          8533.0
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Malta. Residential land at the generic city's densities (75 residents per hectare in deprived areas, 44 elsewhere) until WP3 maps a harmonised urban core. The administrative density in proposal Table 4 is not used: for Lahti and Klagenfurt it includes forest, farmland and lakes, which would make these cities look greener than their residents' surroundings are (feasibility test, 2026-09-19)."
      },
      {
        "var": "Background Green Cover",
        "label": "Background green cover",
        "unit": "%",
        "dp": 1,
        "values": [
          0.06,
          0.14
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Malta: the generic city's values, pending the decision on what green cover means (v5.1 evidence, decision 1). Harmonised data ready for either definition, ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health: green area 25.2 percent of land within 300 m of homes (Urban Atlas 2012; publicly designated green space) and NDVI 0.243 (all vegetation)."
      },
      {
        "var": "Initial NBS Cover",
        "label": "Public green at the start",
        "unit": "%",
        "dp": 1,
        "values": [
          0.04,
          0.08
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, Malta: the generic city's values. To come from the city's own inventory of parks, street trees and other green infrastructure it maintains, or from Urban Atlas 'green urban areas' (WP3)."
      },
      {
        "var": "Municipal NBS Budget",
        "label": "NBS budget",
        "unit": "k EUR/yr",
        "dp": 0,
        "values": [
          22098.0
        ],
        "tag": "PROVISIONAL",
        "note": "PROVISIONAL, calibrated, Malta: 41 euro per resident a year (533,286 residents). Chosen so that the city's public green is roughly stable from 2012, the neutral assumption while the real budget is unknown. The generic city's 96 euro per resident instead implied a 31 percent expansion of public green by 2026, which no European city has achieved (plausibility.py). At this budget the model spends about 29 thousand euro a year per hectare of public green, covering renewal and the municipal organisation as well as upkeep; city park agencies spend on average 12.7 thousand US dollars per hectare on operations alone, range 3.2 to 54.9 (KPMG, Park access, 2017), and UK parks services about 20 to 30 pounds per resident. Replace with the city's reported NBS spending (WP5), or calibrate against the observed change in public green (Urban Atlas 2012, 2018, 2021)."
      },
      {
        "var": "Annual Death Rate",
        "label": "Death rate",
        "unit": "per 1,000/yr",
        "dp": 1,
        "values": [
          0.0072
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Malta. Crude death rate 7.2 per 1,000 residents, NUTS 3 region MT001 Malta, 2023 (Eurostat demo_r_gind3). The region is wider than the city."
      },
      {
        "var": "Baseline Nature Engagement",
        "label": "Use green space without a programme",
        "unit": "%",
        "dp": 0,
        "values": [
          0.213,
          0.255
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Malta. Special Eurobarometer 525 (2022): 20 percent of physically active adults in Malta exercise in a park or outdoors, against 47 percent in the EU. The generic values (0.5, 0.6; White et al. 2019) are scaled by 20/47. National figure; WP4 surveys can replace it."
      },
      {
        "var": "Background Fine Particulates",
        "label": "PM2.5 before policy",
        "unit": "ug/m3",
        "dp": 1,
        "values": [
          20.35,
          16.28
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, Malta. Annual mean PM2.5 17.5 micrograms per cubic metre, ranked 117 of 858 European cities (ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health; proposal Table 4). The split between neighbourhood types is PROVISIONAL, as in the generic city (deprived areas 25 percent higher), with the population-weighted mean equal to 17.5."
      },
      {
        "var": "Poor Mental Health Prevalence",
        "label": "Poor mental health",
        "unit": "%",
        "dp": 1,
        "values": [
          0.126
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Malta. Eurostat EHIS 2019 (hlth_ehis_mh1e): 8.8 percent of adults in Malta report current depressive symptoms, against 7.0 percent in the EU. The generic value (0.10, depression and anxiety, IHME) is scaled by 8.8/7.0. National figure."
      },
      {
        "var": "Delivery Cost per Hectare",
        "label": "Cost to deliver a hectare",
        "unit": "k EUR/ha",
        "dp": 0,
        "values": [
          169.6
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, scaled, Malta. Eurostat price level index for construction, 2024 (prc_ppp_ind, EU27 = 100): Malta 84.8. The generic cost (200, an EU-average city) is scaled by 84.8/100. National figure."
      },
      {
        "var": "Green Cover at Half Access",
        "label": "Green cover at half access",
        "unit": "",
        "dp": 3,
        "values": [
          0.5758
        ],
        "tag": "CITY DATA",
        "note": "CITY DATA, calibrated, Malta. 76.21 percent of residents live where green area within 300 m is below the 25 percent that provides WHO-recommended access (ISGlobal ranking of cities (isglobalranking.org), from Barboza et al. 2021, Lancet Planetary Health, and Khomenko et al. 2021, Lancet Planetary Health; proposal Table 4), so access is 23.79 percent. The value is solved so that the model's access at time 0 matches, given the provisional green cover above; it will be recalibrated when the city's green cover is measured. It measures how well a city's green space is spread among its homes: low where green is close to most residents."
      }
    ],
    "id": "Malta",
    "blurb": "The national conurbation. The most polluted air of the four, and the lowest park use."
  },
  {
    "name": "Hypothetical city",
    "population": 150000.0,
    "rows": [
      {
        "var": "Population",
        "label": "Residents",
        "unit": "people",
        "dp": 0,
        "values": [
          45000.0,
          105000.0
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. CITY PROFILE. Residents of each neighbourhood type."
      },
      {
        "var": "Land Area",
        "label": "Land area",
        "unit": "ha",
        "dp": 0,
        "values": [
          600.0,
          2400.0
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. CITY PROFILE. Land area of each neighbourhood type."
      },
      {
        "var": "Background Green Cover",
        "label": "Background green cover",
        "unit": "%",
        "dp": 1,
        "values": [
          0.06,
          0.14
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. CITY PROFILE. Share of land under green cover that the NBS programme does not manage and that is held constant: private gardens, woodland, natural and agricultural land."
      },
      {
        "var": "Initial NBS Cover",
        "label": "Public green at the start",
        "unit": "%",
        "dp": 1,
        "values": [
          0.04,
          0.08
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. CITY PROFILE. Share of land under programme NBS at the start of the run: parks, street trees and other green infrastructure the city maintains."
      },
      {
        "var": "Municipal NBS Budget",
        "label": "NBS budget",
        "unit": "k EUR/yr",
        "dp": 0,
        "values": [
          14400.0
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. CITY PROFILE. Annual resources the city itself devotes to NBS, in thousand euro, including staff time and managerial attention valued in money."
      },
      {
        "var": "Annual Death Rate",
        "label": "Death rate",
        "unit": "per 1,000/yr",
        "dp": 1,
        "values": [
          0.01
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. CITY PROFILE. Deaths per resident per year, all causes."
      },
      {
        "var": "Baseline Nature Engagement",
        "label": "Use green space without a programme",
        "unit": "%",
        "dp": 0,
        "values": [
          0.5,
          0.6
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. CITY PROFILE. Share of residents with green space nearby who use it regularly without any programme. Varies by culture: the proposal notes 66 percent of Finnish adults exercise in parks against 20 percent of Maltese. New in v5. SOURCE (v5.1): value kept. White et al. 2019, Scientific Reports 9:7730 (England, n=19,806): 33.6 percent of adults spent 120 minutes or more in nature in the past week. Among residents who have green space close by, that is roughly one half; deprived groups visit less, hence 0.5 against 0.6. Set per pilot from WP4 survey data."
      },
      {
        "var": "Background Fine Particulates",
        "label": "PM2.5 before policy",
        "unit": "ug/m3",
        "dp": 1,
        "values": [
          10.0,
          8.0
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. CITY PROFILE. Annual mean PM2.5 before new clean-air measures. New in v5. SOURCE (v5.1): value kept. Proposal Table 4, from the ISGlobal ranking of 858 European cities: Paijat-Hame 5.8, Cork 7.2, Klagenfurt 13.4, Malta 17.5. The WHO 2021 air quality guideline is 5. Deprived areas set higher because they are more often near traffic and industry."
      },
      {
        "var": "Poor Mental Health Prevalence",
        "label": "Poor mental health",
        "unit": "%",
        "dp": 1,
        "values": [
          0.1
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. CITY PROFILE. Share of adults with poor mental health, here the common mental disorders (depression and anxiety) that nature contact is linked to. New in v5. SOURCE (v5.1): 0.15 -> 0.1. OECD/EC Health at a Glance: Europe 2018, from IHME estimates for 2016: anxiety disorders 5.4 percent and depressive disorders 4.5 percent of the EU population; any mental health problem, including substance use, 17.3 percent. Set per pilot from national data or WP6."
      },
      {
        "var": "Delivery Cost per Hectare",
        "label": "Cost to deliver a hectare",
        "unit": "k EUR/ha",
        "dp": 0,
        "values": [
          200.0
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. Resources needed to deliver one hectare of functioning green cover at perfect quality, in thousand euro."
      },
      {
        "var": "Green Cover at Half Access",
        "label": "Green cover at half access",
        "unit": "",
        "dp": 3,
        "values": [
          0.69
        ],
        "tag": "GENERIC CITY",
        "note": "GENERIC CITY. Green cover share at which half of residents have green space close to home (the WHO recommendation used by ISGlobal: at least 0.5 ha within 300 m, the 300 of 3-30-300). SOURCE (v5.1): 0.2 -> 0.69, calibrated. Across European cities 62 percent of residents lack this access (Barboza et al. 2021, Lancet Planetary Health 5:e718-e730) while green and blue infrastructure covers 42 percent of urban area on average (EEA 2022, Who benefits from nature in cities?). Solving access = cover / ( cover + h ) gives h = 0.42 x 0.62 / 0.38 = 0.69. Recalibrate per pilot with h = cover x ( 1 - access ) / access, using Table 4 access (Paijat-Hame 67.6, Cork 21.3, Klagenfurt 34.8, Malta 23.8 percent) and the pilot's green cover."
      }
    ],
    "id": "Generic",
    "blurb": "Not a real place: a mid-size city used as a reference point. It anchors the model back to its earliest version and keeps the abstract budget, so its spending per hectare is higher than any pilot's."
  }
]

export const INPUTS = [
  {
    "name": "Policy Start Year",
    "base": "Policy Start Year",
    "city": null,
    "label": "Policy starts in",
    "unit": "",
    "group": "timing",
    "default": 2027.0,
    "min": 2012,
    "max": 2060,
    "help": "The year the policy settings take effect."
  },
  {
    "name": "Share of New NBS in Deprived Areas",
    "base": "Share of New NBS in Deprived Areas",
    "city": null,
    "label": "New green space going to deprived areas",
    "unit": "share",
    "group": "lever",
    "default": 0.2,
    "min": 0.0,
    "max": 1.0,
    "help": "Share of the rollout budget spent in deprived neighbourhoods."
  },
  {
    "name": "Displacement Safeguards",
    "base": "Displacement Safeguards",
    "city": null,
    "label": "Anti-displacement safeguards",
    "unit": "strength",
    "group": "lever",
    "default": 0.2,
    "min": 0.0,
    "max": 1.0,
    "help": "Strength of anti-displacement measures that accompany greening: rent protection, social housing, community land trusts, just-green-enough design."
  },
  {
    "name": "Cross Sectoral Integration",
    "base": "Cross Sectoral Integration",
    "city": null,
    "label": "Cross-sectoral integration",
    "unit": "strength",
    "group": "lever",
    "default": 0.2,
    "min": 0.0,
    "max": 1.0,
    "help": "Degree to which water, health, transport and housing departments co-plan and co-fund NBS through shared targets and budgets."
  },
  {
    "name": "Share of Resources to Nature Programmes",
    "base": "Share of Resources to Nature Programmes",
    "city": null,
    "label": "Budget spent on nature programmes",
    "unit": "share",
    "group": "lever",
    "default": 0.0,
    "min": 0.0,
    "max": 0.5,
    "help": "Share of NBS resources spent getting people into green space rather than building or keeping it."
  },
  {
    "name": "Clean Air Policy Emission Cut",
    "base": "Clean Air Policy Emission Cut",
    "city": null,
    "label": "Clean-air policy: cut in emissions",
    "unit": "share",
    "group": "lever",
    "default": 0.0,
    "min": 0.0,
    "max": 0.9,
    "help": "Fractional cut in PM2.5 from clean-air and transport policy, outside the NBS programme."
  },
  {
    "name": "Budget Change from Policy Start",
    "base": "Budget Change from Policy Start",
    "city": null,
    "label": "Change to the NBS budget",
    "unit": "x",
    "group": "lever",
    "default": 1.0,
    "min": 0.0,
    "max": 3.0,
    "help": "What the city decides to do to its NBS budget from the policy start year: 1 leaves it as it is, 1.5 raises it by half."
  },
  {
    "name": "Maximum Rollout Share",
    "base": "Maximum Rollout Share",
    "city": null,
    "label": "Cap on spending diverted to rollout",
    "unit": "share",
    "group": "posture",
    "default": 0.7,
    "min": 0.0,
    "max": 1.0,
    "help": "Cap on the share of resources that can be diverted to immediate rollout."
  },
  {
    "name": "Pressure at Half Share",
    "base": "Pressure at Half Share",
    "city": null,
    "label": "Pressure at which the city swings half way",
    "unit": "",
    "group": "posture",
    "default": 0.35,
    "min": 0.01,
    "max": 5.0,
    "help": "Rollout pressure at which the city has swung half way to its cap."
  },
  {
    "name": "Staff and Knowledge Loss",
    "base": "Staff and Knowledge Loss",
    "city": null,
    "label": "Staff and knowledge lost each year",
    "unit": "per year",
    "group": "posture",
    "default": 0.05,
    "min": 0.0,
    "max": 0.5,
    "help": "Fractional annual loss of skills, staff and institutional memory."
  },
  {
    "name": "Ambition Scale",
    "base": "Ambition Scale",
    "city": null,
    "label": "Ambition when support is at its highest",
    "unit": "",
    "group": "posture",
    "default": 0.9,
    "min": 0.0,
    "max": 1.0,
    "help": "Performance the city aims for when support is at its maximum."
  },
  {
    "name": "Green Cover Target",
    "base": "Green Cover Target",
    "city": null,
    "label": "Green cover target",
    "unit": "share of land",
    "group": "profile",
    "default": 0.3,
    "min": 0.01,
    "max": 1.0,
    "help": "CITY PROFILE."
  },
  {
    "name": "Mortality Reduction per Unit Green Cover",
    "base": "Mortality Reduction per Unit Green Cover",
    "city": null,
    "label": "Mortality Reduction per Unit Green Cover",
    "unit": "",
    "group": "evidence",
    "default": 0.2,
    "min": 0.0,
    "max": 0.5,
    "help": "Fraction of annual deaths avoided per unit of green cover share: 0.2 means 10 percentage points of cover lowers mortality by 2 percent."
  },
  {
    "name": "Summer Cooling per Unit Green Cover",
    "base": "Summer Cooling per Unit Green Cover",
    "city": null,
    "label": "Summer Cooling per Unit Green Cover",
    "unit": "",
    "group": "evidence",
    "default": 2.0,
    "min": 0.0,
    "max": 10.0,
    "help": "Summer air-temperature reduction per unit of green cover share: 2 means each 10 percentage points of cover cools by 0.2 degC."
  },
  {
    "name": "Heat Mortality Reduction per Degree",
    "base": "Heat Mortality Reduction per Degree",
    "city": null,
    "label": "Heat Mortality Reduction per Degree",
    "unit": "",
    "group": "evidence",
    "default": 0.007,
    "min": 0.0,
    "max": 0.05,
    "help": "Fraction of annual deaths avoided per degree of summer cooling."
  },
  {
    "name": "Mental Health Risk Reduction from Nature Use",
    "base": "Mental Health Risk Reduction from Nature Use",
    "city": null,
    "label": "Mental Health Risk Reduction from Nature Use",
    "unit": "",
    "group": "evidence",
    "default": 0.25,
    "min": 0.0,
    "max": 1.0,
    "help": "Fraction by which regular nature use lowers the risk of poor mental health."
  },
  {
    "name": "Municipal NBS Budget[Generic]",
    "base": "Municipal NBS Budget",
    "city": "Generic",
    "label": "NBS budget",
    "unit": "k EUR a year",
    "group": "profile",
    "default": 14400.0,
    "min": 0.0,
    "max": 43200.0,
    "help": "CITY PROFILE."
  },
  {
    "name": "Municipal NBS Budget[Cork]",
    "base": "Municipal NBS Budget",
    "city": "Cork",
    "label": "NBS budget",
    "unit": "k EUR a year",
    "group": "profile",
    "default": 10461.0,
    "min": 0.0,
    "max": 31400.0,
    "help": "Chosen so that the city's public green is roughly stable from 2012, the neutral assumption while the real budget is unknown."
  },
  {
    "name": "Municipal NBS Budget[Klagenfurt]",
    "base": "Municipal NBS Budget",
    "city": "Klagenfurt",
    "label": "NBS budget",
    "unit": "k EUR a year",
    "group": "profile",
    "default": 5622.0,
    "min": 0.0,
    "max": 16900.0,
    "help": "Chosen so that the city's public green is roughly stable from 2012, the neutral assumption while the real budget is unknown."
  },
  {
    "name": "Municipal NBS Budget[Lahti]",
    "base": "Municipal NBS Budget",
    "city": "Lahti",
    "label": "NBS budget",
    "unit": "k EUR a year",
    "group": "profile",
    "default": 6538.0,
    "min": 0.0,
    "max": 19600.0,
    "help": "Chosen so that the city's public green is roughly stable from 2012, the neutral assumption while the real budget is unknown."
  },
  {
    "name": "Municipal NBS Budget[Malta]",
    "base": "Municipal NBS Budget",
    "city": "Malta",
    "label": "NBS budget",
    "unit": "k EUR a year",
    "group": "profile",
    "default": 22098.0,
    "min": 0.0,
    "max": 66300.0,
    "help": "Chosen so that the city's public green is roughly stable from 2012, the neutral assumption while the real budget is unknown."
  },
  {
    "name": "Delivery Cost per Hectare[Generic]",
    "base": "Delivery Cost per Hectare",
    "city": "Generic",
    "label": "Cost to deliver a hectare",
    "unit": "k EUR",
    "group": "profile",
    "default": 200.0,
    "min": 0.0,
    "max": 600.0,
    "help": "Resources needed to deliver one hectare of functioning green cover at perfect quality, in thousand euro.."
  },
  {
    "name": "Delivery Cost per Hectare[Cork]",
    "base": "Delivery Cost per Hectare",
    "city": "Cork",
    "label": "Cost to deliver a hectare",
    "unit": "k EUR",
    "group": "profile",
    "default": 192.6,
    "min": 0.0,
    "max": 600.0,
    "help": "Eurostat price level index for construction, 2024 (prc_ppp_ind, EU27 = 100): Ireland 96.3."
  },
  {
    "name": "Delivery Cost per Hectare[Klagenfurt]",
    "base": "Delivery Cost per Hectare",
    "city": "Klagenfurt",
    "label": "Cost to deliver a hectare",
    "unit": "k EUR",
    "group": "profile",
    "default": 223.4,
    "min": 0.0,
    "max": 700.0,
    "help": "Eurostat price level index for construction, 2024 (prc_ppp_ind, EU27 = 100): Austria 111.7."
  },
  {
    "name": "Delivery Cost per Hectare[Lahti]",
    "base": "Delivery Cost per Hectare",
    "city": "Lahti",
    "label": "Cost to deliver a hectare",
    "unit": "k EUR",
    "group": "profile",
    "default": 222.8,
    "min": 0.0,
    "max": 700.0,
    "help": "Eurostat price level index for construction, 2024 (prc_ppp_ind, EU27 = 100): Finland 111.4."
  },
  {
    "name": "Delivery Cost per Hectare[Malta]",
    "base": "Delivery Cost per Hectare",
    "city": "Malta",
    "label": "Cost to deliver a hectare",
    "unit": "k EUR",
    "group": "profile",
    "default": 169.6,
    "min": 0.0,
    "max": 500.0,
    "help": "Eurostat price level index for construction, 2024 (prc_ppp_ind, EU27 = 100): Malta 84.8."
  }
]

export const EVIDENCE = {
  "Mortality Reduction per Unit Green Cover": [
    0.12,
    0.32
  ],
  "Summer Cooling per Unit Green Cover": [
    1.0,
    6.0
  ],
  "Heat Mortality Reduction per Degree": [
    0.005,
    0.011
  ],
  "Mental Health Risk Reduction from Nature Use": [
    0.08,
    0.4
  ]
}

export const START_YEAR = 2012
export const END_YEAR = 2075
export const TODAY = 2026
